"""add paid_months

Revision ID: 3993b05555ae
Revises: 4d0579c5b55a
Create Date: 2026-06-14 22:03:36.630941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3993b05555ae'
down_revision: Union[str, Sequence[str], None] = '4d0579c5b55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('paid_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debts', 'paid_months')
    # ### end Alembic commands ###
