"""Add alias and photo_url to User

Revision ID: 78e4f0ec5c63
Revises: 62e37f8ccf9b
Create Date: 2026-07-12 00:25:35.680933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78e4f0ec5c63'
down_revision: Union[str, Sequence[str], None] = '62e37f8ccf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('space_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'spaces', ['space_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('alias')

    with op.batch_alter_table('investment_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('space_id')
        batch_op.drop_column('color')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
